/*
 * Timer1.c
 *
 *  Created on: Oct 11, 2022
 *      Author: mohamed
 */

#include "Timer1.h"
//******************************************TIMER1***************************************************
void TIMER1_init(void)
{
#if TIMER1_MODE == NORMAL
	// None
#if TIMER1_INT_MODE == ENABLED
	SET_BIT(TIMSK,TOIE1) ;

#endif
#elif TIMER1_MODE == PWM_PC_8
	SET_BIT(TCCR1A,WGM10) ;

#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif

#elif TIMER1_MODE == PWM_PC_9
	 SET_BIT(TCCR1A,WGM11) ;

#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif
#elif TIMER1_MODE == PWM_PC_10
	 SET_BIT(TCCR1A,WGM11) ;
	 SET_BIT(TCCR1A,WGM10) ;
#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif
#elif TIMER1_MODE == CTC_TOP_OCR1A //*********************
	 SET_BIT(TCCR1B,WGM12) ;
#if TIMER1_CTC_OC0_MODE == TOG_OC0
	SET_BIT(TCCR1A,COM1A0) ;
	CLR_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_CTC_OC0_MODE == NORMAL
	CLR_BIT(TCCR1A,COM1A0) ;
	CLR_BIT(TCCR1A,COM1A1) ;
#elif TIMER1_CTC_OC0_MODE == CLR_OC0
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;
#elif TIMER1_CTC_OC0_MODE == SET_OC0
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;
#endif
#if TIMER1_INT_MODE == ENABLED
	SET_BIT(TIMSK,OCIE1A) ;
#endif
#elif TIMER1_MODE == PWM_FAST_8
	 SET_BIT(TCCR1A,WGM10) ;
	 SET_BIT(TCCR1B,WGM12) ;
#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif
#elif TIMER1_MODE == PWM_FAST_9
	 SET_BIT(TCCR1A,WGM11) ;
	 SET_BIT(TCCR1B,WGM12) ;

#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif
#elif TIMER1_MODE == PWM_FAST_10
	 SET_BIT(TCCR1A,WGM10) ;
	 SET_BIT(TCCR1A,WGM11) ;
	 SET_BIT(TCCR1B,WGM12) ;

#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif
#elif TIMER1_MODE == PWM_PFC_TOP_ICR1
	 SET_BIT(TCCR1B,WGM13) ;
#elif TIMER1_MODE == PWM_PFC_TOP_OCR1A
	 SET_BIT(TCCR1B,WGM13) ;
	 SET_BIT(TCCR1A,WGM10) ;
#elif TIMER1_MODE == PWM_PC_TOP_ICR1
	 SET_BIT(TCCR1B,WGM13) ;
	 SET_BIT(TCCR1A,WGM11) ;
#elif TIMER1_MODE == PWM_PC_TOP_OCR1A
	 SET_BIT(TCCR1B,WGM13) ;
	 SET_BIT(TCCR1A,WGM11) ;
	 SET_BIT(TCCR1A,WGM10) ;
#elif TIMER1_MODE == CTC_TOP_ICR1 // ********************************
	 SET_BIT(TCCR1B,WGM13) ;
	 SET_BIT(TCCR1B,WGM12) ;

//******************************************************************
#if TIMER1_CTC_OC0_MODE == TOG_OC0
	SET_BIT(TCCR1A,COM1A0) ;
	CLR_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_CTC_OC0_MODE == NORMAL
	CLR_BIT(TCCR1A,COM1A0) ;
	CLR_BIT(TCCR1A,COM1A1) ;
#elif TIMER1_CTC_OC0_MODE == CLR_OC0
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;
#elif TIMER1_CTC_OC0_MODE == SET_OC0
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;
#endif
//***********************************
#if TIMER1_INT_MODE == ENABLED
	SET_BIT(TIMSK,TICIE1) ;
#endif
#elif TIMER1_MODE == PWM_FAST_TOP_ICR1
	 SET_BIT(TCCR1B,WGM13) ;
	 SET_BIT(TCCR1B,WGM12) ;
	 SET_BIT(TCCR1A,WGM11) ;
#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif
#elif TIMER1_MODE == PWM_FAST_TOP_OCR1A
	 SET_BIT(TCCR1B,WGM13) ;
	 SET_BIT(TCCR1B,WGM12) ;
	 SET_BIT(TCCR1A,WGM11) ;
	 SET_BIT(TCCR1A,WGM10) ;
#if TIMER1_PWM_MODE == INV_PWM
	SET_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#elif TIMER1_PWM_MODE == NON_INVERT_PWM
	CLR_BIT(TCCR1A,COM1A0) ;
	SET_BIT(TCCR1A,COM1A1) ;

#endif
#if TIMER1_INT_MODE == ENABLED
	SET_BIT(TIMSK,OCIE0) ;
#endif
#endif
 // ****************PRESCALAR****************************************
#if	TIMER1_PRESC == NOPRESC
		SET_BIT(TCCR1B,CS10) ;
		CLR_BIT(TCCR1B,CS11) ;
		CLR_BIT(TCCR1B,CS12) ;
#elif TIMER1_PRESC == PRESC_8
		CLR_BIT(TCCR1B,CS10) ;
		SET_BIT(TCCR1B,CS11) ;
		CLR_BIT(TCCR1B,CS12) ;
#elif TIMER1_PRESC == PRESC_64
		SET_BIT(TCCR1B,CS10) ;
		SET_BIT(TCCR1B,CS11) ;
		CLR_BIT(TCCR1B,CS12) ;
#elif TIMER1_PRESC == PRESC_256
		CLR_BIT(TCCR1B,CS10) ;
		CLR_BIT(TCCR1B,CS11) ;
		SET_BIT(TCCR1B,CS12) ;

#elif TIMER1_PRESC == PRESC_1024
		SET_BIT(TCCR1B,CS10) ;
		CLR_BIT(TCCR1B,CS11) ;
		SET_BIT(TCCR1B,CS12) ;
#elif TIMER1_PRESC == EXT_CLKT0_FALLING
		CLR_BIT(TCCR1B,CS10) ;
		SET_BIT(TCCR1B,CS11) ;
		SET_BIT(TCCR1B,CS12) ;
#elif TIMER1_PRESC == EXT_CLKT0_RISING
		SET_BIT(TCCR1B,CS10) ;
		SET_BIT(TCCR1B,CS11) ;
		SET_BIT(TCCR1B,CS12) ;
#endif


}
void TIMER1_delay(uint32_t counter)
{while (counter--)
  {
	while (GET_BIT(TIFR,TOV1) == 0) ;
	TCNT1 = 0 ;
	SET_BIT(TIFR,TOV1) ;
  }

}
void TIMER1_stop()
{

			CLR_BIT(TCCR1B,CS10) ;
			CLR_BIT(TCCR1B,CS11) ;
			CLR_BIT(TCCR1B,CS12) ;


}
